# Generated by Django 3.2.4 on 2021-07-15 12:11

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('sherbim', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shto_sherbim',
            name='sherbimi_rradhes',
            field=models.DateField(default=datetime.datetime(2021, 10, 23, 12, 11, 7, 246869, tzinfo=utc)),
        ),
    ]
