# Generated by Django 3.2.4 on 2021-07-12 07:58

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('makina', '__first__'),
        ('punonjes', '__first__'),
        ('sherbim', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shto_Sherbim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kategoria', models.CharField(choices=[('Nderrim Vaji dhe Filtra', 'Nderrim Vaji dhe Filtra')], max_length=50)),
                ('date_sherbimi', models.DateField(default=datetime.date(2021, 7, 12))),
                ('sherbimi_rradhes', models.DateField(default=datetime.date(2021, 7, 12))),
                ('cmimi', models.DecimalField(decimal_places=2, max_digits=999999)),
                ('paguar', models.BooleanField(default=False)),
                ('verifikuar', models.BooleanField(default=False)),
                ('makaniku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='punonjes.punonjes')),
                ('makina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='makina.makina')),
                ('sherbim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sherbim.sherbimi')),
            ],
        ),
    ]
