# Generated by Django 3.2.4 on 2021-07-12 08:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sherbim', '0002_shto_sherbim'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shto_sherbim',
            name='date_sherbimi',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='shto_sherbim',
            name='sherbimi_rradhes',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
