# Generated by Django 3.2.4 on 2021-07-12 08:50

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('sherbim', '0003_auto_20210712_1007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shto_sherbim',
            name='sherbimi_rradhes',
            field=models.DateField(default=datetime.datetime(2021, 10, 20, 8, 50, 21, 376125, tzinfo=utc)),
        ),
    ]
