# Generated by Django 3.2.4 on 2021-08-03 13:01

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('sherbim', '0006_alter_shto_sherbim_sherbimi_rradhes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shto_sherbim',
            old_name='sherbim',
            new_name='lloj_sherbimi',
        ),
        migrations.AlterField(
            model_name='shto_sherbim',
            name='sherbimi_rradhes',
            field=models.DateField(default=datetime.datetime(2021, 11, 11, 13, 0, 59, 135082, tzinfo=utc)),
        ),
    ]
