# Generated by Django 3.2.4 on 2021-08-20 14:21

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('sherbim', '0014_auto_20210816_1132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shto_sherbim',
            name='sherbimi_rradhes',
            field=models.DateField(default=datetime.datetime(2021, 11, 28, 14, 21, 52, 710071, tzinfo=utc)),
        ),
    ]
