# Generated by Django 3.2.4 on 2021-08-02 14:10

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sherbim', '0006_alter_shto_sherbim_sherbimi_rradhes'),
        ('klient', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rezervim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_fillimi', models.DateTimeField(default=datetime.datetime(2021, 8, 2, 16, 10, 13, 660914))),
                ('date_mbarimi', models.DateTimeField(default=datetime.datetime(2021, 8, 3, 14, 10, 13, 660914, tzinfo=utc))),
                ('cmimi', models.DecimalField(decimal_places=2, default=0, max_digits=9999999)),
                ('klient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='klient.klient')),
                ('sherbim1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shrbim2', to='sherbim.shto_sherbim')),
                ('sherbim2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shrbim3', to='sherbim.shto_sherbim')),
                ('sherbim3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shrbim4', to='sherbim.shto_sherbim')),
                ('sherbim4', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shrbim5', to='sherbim.shto_sherbim')),
                ('sherbim5', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shrbim6', to='sherbim.shto_sherbim')),
                ('sherbim6', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shrbim7', to='sherbim.shto_sherbim')),
                ('sherbim7', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shrbim8', to='sherbim.shto_sherbim')),
                ('sherbim8', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shrbim9', to='sherbim.shto_sherbim')),
                ('sherbim9', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shrbim0', to='sherbim.shto_sherbim')),
            ],
        ),
    ]
