# Generated by Django 3.2.4 on 2021-08-04 06:51

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('servis', '0003_auto_20210804_0846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rezervim',
            name='date_fillimi',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 4, 8, 51, 13, 396142)),
        ),
        migrations.AlterField(
            model_name='rezervim',
            name='date_mbarimi',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 5, 6, 51, 13, 396142, tzinfo=utc)),
        ),
    ]
