# Generated by Django 3.2.4 on 2021-08-04 14:30

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('servis', '0004_auto_20210804_0851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rezervim',
            name='cmimi',
            field=models.DecimalField(decimal_places=2, max_digits=9999999),
        ),
        migrations.AlterField(
            model_name='rezervim',
            name='date_fillimi',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 4, 16, 30, 34, 272751)),
        ),
        migrations.AlterField(
            model_name='rezervim',
            name='date_mbarimi',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 5, 14, 30, 34, 272751, tzinfo=utc)),
        ),
    ]
