# Generated by Django 3.2.4 on 2021-08-11 08:07

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('servis', '0007_auto_20210809_1126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rezervim',
            name='date_fillimi',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 11, 10, 7, 27, 116404)),
        ),
        migrations.AlterField(
            model_name='rezervim',
            name='date_mbarimi',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 12, 8, 7, 27, 116404, tzinfo=utc)),
        ),
    ]
