# Generated by Django 3.2.4 on 2021-08-12 08:57

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('servis', '0008_auto_20210811_1007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rezervim',
            name='date_fillimi',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 12, 10, 57, 5, 797174)),
        ),
        migrations.AlterField(
            model_name='rezervim',
            name='date_mbarimi',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 13, 8, 57, 5, 797174, tzinfo=utc)),
        ),
    ]
