# Generated by Django 3.2.4 on 2021-08-16 09:32

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('servis', '0009_auto_20210812_1057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rezervim',
            name='date_fillimi',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 16, 11, 32, 2, 320846)),
        ),
        migrations.AlterField(
            model_name='rezervim',
            name='date_mbarimi',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 17, 9, 32, 2, 320846, tzinfo=utc)),
        ),
    ]
