# Generated by Django 3.2.4 on 2021-08-20 14:21

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('servis', '0010_auto_20210816_1132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rezervim',
            name='date_fillimi',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 20, 16, 21, 52, 711068)),
        ),
        migrations.AlterField(
            model_name='rezervim',
            name='date_mbarimi',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 21, 14, 21, 52, 711068, tzinfo=utc)),
        ),
    ]
